ARG RHEL_VERSION
FROM registry.access.redhat.com/ubi9/ubi-init:${RHEL_VERSION}

ENV SMDEV_CONTAINER_OFF=1
ENV LOG_LEVEL=trace

RUN --mount=type=secret,id=rhsm_org \
    --mount=type=secret,id=rhsm_activationkey \
    subscription-manager register --name=fdo-image-builder --org=$(cat /run/secrets/rhsm_org) --activationkey=$(cat /run/secrets/rhsm_activationkey)

RUN dnf update -y && dnf install -y fdo-owner-onboarding-server && dnf clean all

RUN subscription-manager unregister

RUN mkdir -p /etc/fdo/sessions
RUN mkdir -p /etc/fdo/owner-onboarding-server.conf.d
RUN mkdir -p /etc/fdo/ownership_vouchers
RUN mkdir -p /etc/fdo/keys

RUN chmod -R 775 /etc/fdo

EXPOSE 8081
ENTRYPOINT ["/usr/libexec/fdo/fdo-owner-onboarding-server"]