FROM registry.access.redhat.com/ubi9/ubi-init:9.3

ARG RHSM_ORG
ARG RHSM_ACTIVATIONKEY

ENV LOG_LEVEL=info

RUN subscription-manager register --name=rhcos-driver-builder --org=${RHSM_ORG} --activationkey=${RHSM_ACTIVATIONKEY}

RUN dnf update -y && dnf install -y fdo-owner-cli && dnf clean all

RUN subscription-manager unregister

RUN mkdir -p /etc/fdo
RUN chmod -R 775 /etc/fdo

ENTRYPOINT ["/usr/libexec/fdo/fdo-owner-tool"]